name: Selenium Test Workflow
on: push
jobs:
 Selenium_Test_Job:
   name: Selenium Test Job
   runs-on: ubuntu-latest
   steps:
     - run: echo "This is running inside a ${{ runner.os }} server in Github"
     - name: Checkout source code
       uses: actions/checkout@v3.3.0
     - run: echo "This repository is ${{ github.repository }}.."
     - name: Run a inline script
       run: |
         mkdir newfolder
         ls -lrt
       shell: bash
     - name: Run a script file from repo
       run: sh ./run.sh
       shell: pwsh
       
 Selenium_UAT_Job:
   if{{ always() }}
   name: Selenium UAT Job
   runs-on: ubuntu-latest
   needs: Selenium_Test_Job
   steps:
     - run: echo "This is UAT job"
